vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build_and_deploy:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
      - run:
          name: Installing dependencies
          command: |

             sudo apt update
             sudo apt-get install python3-pip
             sudo pip3 install --upgrade pip && pip3 install --upgrade setuptools
             sudo pip3 install ansible boto boto3
             sudo pip3 install cryptography

      - run:
          name: Ansible test
          command: |
            ansible --version

#      - run:
#          name: Let´s go AWS!
#          command: |
#            cd ./ansible && ansible-playbook

workflows:
  version: 2.1
  execute:
      jobs:
        - build_and_deploy


