vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build_and_deploy:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
      - run:
          name: Installing dependencies
          command: |
            sudo apt update -y
            sudo apt install -y curl python-dev git
            sudo curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py"
            sudo python /tmp/get-pip.py
            sudo pip install --upgrade pip && pip install --upgrade setuptools
      - run:
          name: Ansible test
          command: |
            ansible -i


workflows:
  version: 2.1
  execute:
      jobs:
        - build_and_deploy


