vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build_and_deploy:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
      - run:
          name: Installing dependencies
          command: |
            sudo apt update -y
            sudo apt install -y language-pack-ja-base language-pack-ja
            sudo apt install -y software-properties-common
            sudo apt-add-repository -y ppa:ansible/ansible
            sudo apt update -y
            sudo apt install -y curl python-dev git
            sudo curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py"
            sudo python /tmp/get-pip.py
            sudo pip install --upgrade pip && pip install --upgrade setuptools
      - run:
          name: ansible test install
          command: |
            ansible --help

workflows:
  version: 2.1
  execute:
      jobs:
        - build_and_deploy


