vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build_and_deploy:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
      - run:
          name: Installing dependencies
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install ansible boto boto3
      - run:
          name: ansible test install
          command: |
            ansible --help

workflows:
  version: 2.1
  execute:
      jobs:
        - build_and_deploy


