vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build_and_deploy:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
      - run:
          name: Installing dependencies
          command: |
            sudo apt update -y
            sudo python get-pip.py
            sudo apt-get install python3-pip
            sudo pip install --upgrade pip && pip install --upgrade setuptools
            sudo pip install ansible boto boto3

      - run:
          name: Ansible test
          command: |
            ansible --v

workflows:
  version: 2.1
  execute:
      jobs:
        - build_and_deploy


